#!/bin/bash
screen -d -m -S bot bash -c 'source venv/bin/activate && python3 telebot.py'
screen -d -m -S 1 bash -c 'source venv/bin/activate && python3 region_telebot.py 1'
screen -d -m -S 2 bash -c 'source venv/bin/activate && python3 region_telebot.py 2'
screen -d -m -S 3 bash -c 'source venv/bin/activate && python3 region_telebot.py 3'
screen -d -m -S 5 bash -c 'source venv/bin/activate && python3 region_telebot.py 5'
screen -d -m -S 7 bash -c 'source venv/bin/activate && python3 region_telebot.py 7'
screen -d -m -S 8 bash -c 'source venv/bin/activate && python3 region_telebot.py 8'
screen -d -m -S 9 bash -c 'source venv/bin/activate && python3 region_telebot.py 9'
screen -d -m -S 12 bash -c 'source venv/bin/activate && python3 region_telebot.py 12'
screen -d -m -S 13 bash -c 'source venv/bin/activate && python3 region_telebot.py 13'
screen -d -m -S 14 bash -c 'source venv/bin/activate && python3 region_telebot.py 14'
screen -d -m -S 15 bash -c 'source venv/bin/activate && python3 region_telebot.py 15'
screen -d -m -S 16 bash -c 'source venv/bin/activate && python3 region_telebot.py 16'
screen -d -m -S 17 bash -c 'source venv/bin/activate && python3 region_telebot.py 17'
screen -d -m -S 18 bash -c 'source venv/bin/activate && python3 region_telebot.py 18'
screen -d -m -S 19 bash -c 'source venv/bin/activate && python3 region_telebot.py 19'
screen -d -m -S 21 bash -c 'source venv/bin/activate && python3 region_telebot.py 21'
screen -d -m -S 22 bash -c 'source venv/bin/activate && python3 region_telebot.py 22'
screen -d -m -S 23 bash -c 'source venv/bin/activate && python3 region_telebot.py 23'
screen -d -m -S 24 bash -c 'source venv/bin/activate && python3 region_telebot.py 24'
