from decouple import config

TOKEN = config('TOKEN')
ADMIN_ID = config('admin_id', cast=lambda v: [int(s.strip()) for s in v.split(',')])
API_KEY = config('API_KEY')
CHANEL_ID = config('CHANEL_ID', cast=lambda v: [s.strip() for s in v.split(',')])
NOTIFICATION_CHANEL_ID = config('NOTIFICATION_CHANEL_ID')
MYSQL_ROOT_PASSWORD = config('MYSQL_ROOT_PASSWORD')
MYSQL_DATABASE = config('MYSQL_DATABASE')
DATABASE_PASS = config('DATABASE_PASS')
MYSQL_USER = config('MYSQL_USER')
DATABASE_HOST = config('DATABASE_HOST')
ANSWER_TEXT = config('ANSWER_TEXT')
NOTIFICATION_TOKEN = config('NOTIFICATION_TOKEN')
TOKEN_1 = config("TOKEN_1")
TOKEN_2 = config("TOKEN_2")
TOKEN_3 = config("TOKEN_3")
TOKEN_5 = config("TOKEN_5")
# TOKEN_6 = config("TOKEN_6")
TOKEN_7 = config("TOKEN_7")
TOKEN_8 = config("TOKEN_8")
TOKEN_9 = config("TOKEN_9")
TOKEN_12 = config("TOKEN_12")
TOKEN_13 = config("TOKEN_13")
TOKEN_14 = config("TOKEN_14")
TOKEN_15 = config("TOKEN_15")
TOKEN_16 = config("TOKEN_16")
TOKEN_17 = config("TOKEN_17")
TOKEN_18 = config("TOKEN_18")
TOKEN_19 = config("TOKEN_19")
TOKEN_21 = config("TOKEN_21")
TOKEN_22 = config("TOKEN_22")
TOKEN_23 = config("TOKEN_23")
TOKEN_24 = config("TOKEN_24")
